num1 = input("세 자리수 입력:")
num2 = input("세 자리수 입력2 :")
num3 = (int(num1) * int(num2[-1]))
num4 = (int(num1) * int(num2[1]))
num5 = (int(num1) * int(num2[0]))
num6 = num3 + (num4 * 10) + (num5 * 100)
print("   {}".format(num1))
print(" X {}".format(num2))
print("────────")
print("{:7d}".format(num3))
print("{:6d}".format(num4))
print("{:+5d}".format(num5))
print("────────")
print("{:7d}".format(num6))